### ISSUE TITLE
数据集标记的spanx_index的含义？

### ISSUE THREAD

**Issue by learner-crapy** [taishan1994/pytorch_bert_coreference_resolution#2]
作者您好：
我看了您处理好的数据集，以下面这个为例，其中span2_index:27和span1_index:3这个span您是怎么划分的，根据此表还是什么呢？
{"target": {"span2_index": 27, "span1_index": 3, "span1_text": "伤口", "span2_text": "它们"}, "idx": 258, "label": "false", "text": "裂开的伤口涂满尘土，里面有碎石子和木头刺，我小心翼翼把它们剔除出去。"}

**Comment by taishan1994** [comment]
> 作者您好： 我看了您处理好的数据集，以下面这个为例，其中span2_index:27和span1_index:3这个span您是怎么划分的，根据此表还是什么呢？ {"target": {"span2_index": 27, "span1_index": 3, "span1_text": "伤口", "span2_text": "它们"}, "idx": 258, "label": "false", "text": "裂开的伤口涂满尘土，里面有碎石子和木头刺，我小心翼翼把它们剔除出去。"}

span|num_text，表示第num个实体的文本。span|num_index表示第num个实体在文本中的起始位置。

**Comment by learner-crapy** [comment]
thanks

**Comment by learner-crapy** [comment]
作者您好：

 我为再次打扰而感到抱歉，关于数据标注的问题我尚且还有一个问题，spannum_index表示第num个实体在文本中的开始位置，为何不是一个元组或者列表，将该实体在文本中的开始位置和结束位置标出来呢？

西西嘛呦 ***@***.***> 于2023年3月29日周三 09:17写道：

**Comment by taishan1994** [comment]
> 作者您好： 我为再次打扰而感到抱歉，关于数据标注的问题我尚且还有一个问题，spannum_index表示第num个实体在文本中的开始位置，为何不是一个元组或者列表，将该实体在文本中的开始位置和结束位置标出来呢？

1、数据是现有的，它原本就是这样的。
2、而且，上述的应该只针对于句子级别而言，一个句子中实体应该没有那么多。
3、补充，现在大预言模型非常火，完全可以通过构造：给你一个句子：裂开的伤口涂满尘土，里面有碎石子和木头刺，我小心翼翼把它们剔除出去。请判断它们在句子中指代的是什么？这样就不需要标出实体的位置了。

**Comment by learner-crapy** [comment]
好的，谢谢您的答复， all the best!🤓🤓🤓

我刚看了一下源码，在训练过程中确实指定了实体的具体位置，spannum_text给出了实体的文本，spannum_index给出了开始位置，在代码中(spannum_index,spannum_index+len(spannum_text))就确定了实体的位置。

span1_start = span1[1]
span1_end = span1_start + len(span1[0])

for i in range(span1_start, span1_end):
    span1_ids[i] = 1
span2_ids = [0] * len(tokens)
span2_start = span2[1]
span2_end = span2_start + len(span2[0])
for i in range(span2_start, span2_end):
    span2_ids[i] = 1


西西嘛呦 ***@***.***> 于2023年4月2日周日 14:06写道：

**Comment by taishan1994** [comment]
> 好的，谢谢您的答复， all the best!🤓🤓🤓 

这里肯定是用上了的。

**Comment by learner-crapy** [comment]
作者您好，很抱歉再次打扰。

我将训练的日志使用tensorboard可视化了一下，发现一个问题，accuracy，F1，recall，precision这四个指标的值是一样的，我在多个数据集上测试都得到这样的结果：
[image: image.png]
[image: image.png][image: image.png][image: image.png]

按理说情况不应该是这样的，下面是我记录日志的代码
[image: image.png]
请问可能是什么问题导致的呢？

西西嘛呦 ***@***.***> 于2023年4月2日周日 15:18写道：

**Comment by taishan1994** [comment]
是的，我之前也发现了，可能是numpy版本的问题，最好还是自己计算。

**Comment by learner-crapy** [comment]
你是正确的，我打断点调试了一下，如下图所示

![image](https://user-images.githubusercontent.com/69768456/229979639-d7105205-1c40-4f9d-b74b-5d3c319299ea.png)

我保存了trues和pred列表如下：
![image](https://user-images.githubusercontent.com/69768456/229979671-e2814f5b-fd9c-49bb-8bba-d6826b0c7978.png)

得到两个列表，第一行和第二行分别为trues和preds
`[1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0]

[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`

我写了一个类重新将这两个数据对应的那四个指标算了一下，发现它的错误很明显
`

class Metrics:
    def __init__(self, trues, preds):
        self.trues = trues
        self.preds = preds

    def accuracy(self):
        return sum([1 for i in range(len(self.trues)) if self.trues[i] == self.preds[i]]) / len(self.trues)

    def precision(self):
        tp = sum([1 for i in range(len(self.trues)) if self.trues[i] == 1 and self.preds[i] == 1])
        fp = sum([1 for i in range(len(self.trues)) if self.trues[i] == 0 and self.preds[i] == 1])
        return tp / (tp + fp)

    def recall(self):
        tp = sum([1 for i in range(len(self.trues)) if self.trues[i] == 1 and self.preds[i] == 1])
        fn = sum([1 for i in range(len(self.trues)) if self.trues[i] == 1 and self.preds[i] == 0])
        return tp / (tp + fn)

    def f1(self):
        p = self.precision()
        r = self.recall()
        return 2 * p * r / (p + r)

trues = [1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
preds = [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


`
得到如下结果：
![image](https://user-images.githubusercontent.com/69768456/229981076-1d87cbdf-7df7-4ee3-a3f2-6dc63341efeb.png)

西西嘛呦 <notifications@github.com> 于2023年4月5日周三 09:25写道：
是的，我之前也发现了，可能是numpy版本的问题，最好还是自己计算。
